<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJTzMxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJTzMxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJTzMxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJTzMxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXJTzMxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'XJTzMxC',
    'container.build_id' => 'f84b38a7',
    'container.build_time' => 1678100573,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJTzMxC');
